/**
 * Built-in WhatsApp client manager (Baileys).
 *
 * An account is paired by scanning a QR code generated by our own
 * WhatsApp Web session, or by entering an 8-character Pairing Code
 * with the phone number.
 *
 * Each account keeps its own auth state in a per-account folder under
 * `.sessions/<accountId>/` so the session survives server restarts.
 */
import path from 'node:path';
import fs from 'node:fs';
import makeWASocket, {
  type WASocket,
  type AuthenticationState,
  useMultiFileAuthState,
  DisconnectReason,
  Browsers,
  fetchLatestWaWebVersion,
} from '@whiskeysockets/baileys';
import QRCode from 'qrcode';
import { prisma } from '@nexora/database';
import type { GatewayStatus, AccountStatus } from '@nexora/database';
import { maskPhone } from '@nexora/utils';
import { logger, pinoLogger } from '../../common/logger';
import { emitToUser } from '../../common/realtime/socket';
import { handleInbound, handleOutboundSynced, syncWaHistory, cleanJidToPhone } from '../gateway/gateway.service';

export type WaState = 'DISCONNECTED' | 'SCANNING' | 'CONNECTED' | 'FAILED';

interface WaContext {
  userId: string;
  accountId: string;
  socket: WASocket;
  state: WaState;
  qr: string | null;
  pairingCode: string | null;
  error: string | null;
  retryTimer: NodeJS.Timeout | null;
  closed: boolean;
  saveCreds?: () => Promise<void>;
}

const sessions = new Map<string, WaContext>();

const sessionsDir = path.resolve(process.cwd(), '.sessions');

/** The jid suffix for plain phones in Baileys. */
function toWaJid(phone: string): string {
  const digits = phone.replace(/[^\d]/g, '').replace(/^8/, '7');
  return `${digits}@s.whatsapp.net`;
}

function jidToPhone(jid: string): string {
  return jid.split('@')[0]?.split(':')[0] ?? jid;
}

/** Clean phone string to international digits. */
export function sanitizePhone(phone: string): string {
  let digits = phone.replace(/[^\d]/g, '');
  if (digits.startsWith('8') && digits.length === 11) {
    digits = '7' + digits.slice(1);
  }
  return digits;
}

/** Write the real phone number from the linked account into the DB record. */
async function adoptRealPhone(ctx: WaContext): Promise<void> {
  const jid = ctx.socket.user?.id ?? ctx.socket.authState.creds.me?.id ?? '';
  const digits = jidToPhone(jid).replace(/[^\d]/g, '');
  if (digits.length < 7) {
    logger.warn('WA phone not available yet', { accountId: ctx.accountId, jid });
    return;
  }
  try {
    const acc = await prisma.whatsAppAccount.findUnique({ where: { id: ctx.accountId } });
    if (!acc || acc.phone !== digits) {
      await prisma.whatsAppAccount.update({
        where: { id: ctx.accountId },
        data: { phone: digits, phoneMasked: maskPhone(digits) },
      });
      logger.info('WA phone adopted', { accountId: ctx.accountId, phoneMasked: maskPhone(digits) });
    }
  } catch (err) {
    logger.warn('WA phone adopt failed', { accountId: ctx.accountId, error: (err as Error).message });
  }
}

/** Map a Baileys state to our GatewayStatus + AccountStatus pair. */
function toStatuses(ctx: WaContext): { gw: GatewayStatus; acc: AccountStatus } {
  switch (ctx.state) {
    case 'CONNECTED':
      return { gw: 'CONNECTED', acc: 'ONLINE' };
    case 'FAILED':
      return { gw: 'FAILED', acc: 'ATTENTION' };
    case 'SCANNING':
      return { gw: 'SCANNING', acc: 'ATTENTION' };
    default:
      return { gw: 'DISCONNECTED', acc: 'OFFLINE' };
  }
}

/** Encode a raw QR string to base64 PNG (crisp 360px with margin). */
async function qrToBase64(text: string): Promise<string | null> {
  try {
    const dataUrl = await QRCode.toDataURL(text, {
      width: 360,
      margin: 2,
      errorCorrectionLevel: 'M',
      color: {
        dark: '#000000',
        light: '#ffffff',
      },
    });
    return dataUrl.replace(/^data:image\/png;base64,/, '');
  } catch (err) {
    logger.warn('qr encode failed', { error: (err as Error).message });
    return null;
  }
}

function ensureSessionsDir(): void {
  try {
    if (!fs.existsSync(sessionsDir)) fs.mkdirSync(sessionsDir, { recursive: true });
  } catch (err) {
    logger.warn('cannot create sessions dir', { error: (err as Error).message });
  }
}

async function persistStatus(ctx: WaContext): Promise<void> {
  const { gw, acc } = toStatuses(ctx);
  try {
    await prisma.gatewayConnection.upsert({
      where: { accountId: ctx.accountId },
      update: {
        provider: 'WHATSAPP_WEB',
        status: gw,
        lastError: ctx.error,
      },
      create: {
        accountId: ctx.accountId,
        provider: 'WHATSAPP_WEB',
        idInstance: '',
        apiToken: '',
        status: gw,
        lastError: ctx.error,
      },
    });
    await prisma.whatsAppAccount.update({
      where: { id: ctx.accountId },
      data: {
        status: acc,
        lastActiveAt: acc === 'ONLINE' ? new Date() : undefined,
      },
    });
  } catch (err) {
    logger.warn('persist WA status failed', { accountId: ctx.accountId, error: (err as Error).message });
  }
  emitToUser(ctx.userId, 'account.gateway.status', {
    accountId: ctx.accountId,
    status: gw,
    lastError: ctx.error ?? undefined,
  });
}

async function setState(ctx: WaContext, state: WaState, error?: string | null): Promise<void> {
  ctx.state = state;
  ctx.error = error ?? null;
  await persistStatus(ctx);
}

function scheduleReconnect(userId: string, accountId: string, delayMs = 3000): void {
  const timer = setTimeout(() => {
    void startWaSession(userId, accountId).catch((err) => {
      logger.warn('scheduled reconnect failed', { accountId, error: (err as Error).message });
    });
  }, delayMs);
  timer.unref?.();
}

function attachEvents(ctx: WaContext): void {
  ctx.socket.ev.on('creds.update', () => {
    if (sessions.get(ctx.accountId) !== ctx) return;
    void ctx.saveCreds?.().catch((err) => {
      logger.warn('failed to save creds', { accountId: ctx.accountId, error: (err as Error).message });
    });
  });

  ctx.socket.ev.on('connection.update', (update) => {
    if (sessions.get(ctx.accountId) !== ctx || ctx.closed) return;
    const { connection, qr, lastDisconnect, isNewLogin } = update;

    if (qr) {
      logger.info('WA QR received', { accountId: ctx.accountId, len: qr.length });
      void qrToBase64(qr).then((b64) => {
        if (sessions.get(ctx.accountId) !== ctx || ctx.closed) return;
        ctx.qr = b64;
        void setState(ctx, 'SCANNING');
        emitToUser(ctx.userId, 'account.wa.qr', { accountId: ctx.accountId, qr: b64 });
      });
      return;
    }

    if (connection === 'connecting') {
      if (ctx.state !== 'SCANNING') {
        void setState(ctx, 'SCANNING');
      }
      return;
    }

    if (connection === 'open') {
      ctx.qr = null;
      ctx.pairingCode = null;
      void setState(ctx, 'CONNECTED');
      void adoptRealPhone(ctx);
      if (ctx.retryTimer) {
        clearTimeout(ctx.retryTimer);
        ctx.retryTimer = null;
      }
      logger.info('WA session open', { accountId: ctx.accountId, isNewLogin: !!isNewLogin });
      return;
    }

    if (connection === 'close') {
      const error = lastDisconnect?.error;
      const code = (error as { output?: { statusCode?: number } } | undefined)?.output?.statusCode;
      logger.warn('WA session closed', {
        accountId: ctx.accountId,
        code,
        errorName: error?.name,
        errorMessage: error?.message,
      });

      // Mark this context closed so no further events affect state
      ctx.closed = true;
      try {
        ctx.socket.end(undefined);
      } catch {
        /* ignore */
      }
      sessions.delete(ctx.accountId);

      const refsExhausted = code === 408 && /qr refs attempts ended/i.test(error?.message ?? '');
      const loggedOut = code === DisconnectReason.loggedOut || code === DisconnectReason.badSession;

      if (loggedOut || refsExhausted) {
        const message = refsExhausted
          ? 'QR-код устарел. Нажмите «Обновить QR», чтобы получить новый.'
          : 'Сессия завершена. Авторизуйтесь заново через QR или код.';
        void setState(ctx, 'DISCONNECTED', message);
        void purgeSessionFolder(ctx.accountId);
        return;
      }

      // Reconnect immediately for restartRequired (515) which happens upon successful QR scan!
      if (code === DisconnectReason.restartRequired || code === 515) {
        logger.info('WA restartRequired handshake, reconnecting immediately...', { accountId: ctx.accountId });
        scheduleReconnect(ctx.userId, ctx.accountId, 500);
        return;
      }

      // Transient drop (network, connection lost) — reconnect after brief delay
      void setState(ctx, 'SCANNING', null);
      scheduleReconnect(ctx.userId, ctx.accountId, 3000);
    }
  });

  ctx.socket.ev.on('messages.upsert', async ({ messages, type }) => {
    if (sessions.get(ctx.accountId) !== ctx || ctx.closed) return;
    logger.info('WA messages.upsert event', {
      accountId: ctx.accountId,
      type,
      count: messages.length,
    });

    for (const m of messages) {
      try {
        const phone = await resolveJidToPhone(ctx, m);
        if (!phone) {
          logger.debug('Skipping WA message without phone', {
            remoteJid: m.key?.remoteJid,
            remoteJidAlt: m.key?.remoteJidAlt,
          });
          continue;
        }

        const text = extractTextFromRaw(m);
        if (!text) {
          logger.debug('Skipping empty/unsupported WA message payload', {
            key: m.key,
            messageTypes: Object.keys(m.message || {}),
          });
          continue;
        }

        const opId = m.key?.id ?? undefined;
        const ts = m.messageTimestamp ? Number(m.messageTimestamp) * 1000 : Date.now();
        const fromMe = Boolean(m.key?.fromMe);

        logger.info('Incoming/Outgoing WA message received', {
          accountId: ctx.accountId,
          phone,
          fromMe,
          opId,
          text: text.slice(0, 60),
        });

        if (fromMe) {
          await handleOutboundSynced(ctx.userId, ctx.accountId, {
            chatId: phone,
            text,
            opId,
            timestamp: ts,
          });
        } else {
          await handleInbound(ctx.userId, ctx.accountId, {
            chatId: phone,
            text,
            opId,
            senderName: m.pushName ?? undefined,
            timestamp: ts,
          });
        }
      } catch (err) {
        logger.warn('Failed to process message in messages.upsert', {
          accountId: ctx.accountId,
          error: (err as Error).message,
        });
      }
    }
  });

  ctx.socket.ev.on('messaging-history.set', (history) => {
    if (sessions.get(ctx.accountId) !== ctx || ctx.closed) return;
    logger.info('WA messaging-history.set received', {
      accountId: ctx.accountId,
      chats: history.chats?.length ?? 0,
      contacts: history.contacts?.length ?? 0,
      messages: history.messages?.length ?? 0,
    });
    void syncWaHistory(ctx.userId, ctx.accountId, history as never).catch((err) => {
      logger.warn('WA history sync failed', { accountId: ctx.accountId, error: (err as Error).message });
    });
  });

  ctx.socket.ev.on('chats.upsert', (chats) => {
    if (sessions.get(ctx.accountId) !== ctx || ctx.closed) return;
    void syncWaHistory(ctx.userId, ctx.accountId, { chats: chats as never }).catch((err) => {
      logger.warn('WA chats.upsert failed', { accountId: ctx.accountId, error: (err as Error).message });
    });
  });

  ctx.socket.ev.on('chats.update', (chats) => {
    if (sessions.get(ctx.accountId) !== ctx || ctx.closed) return;
    void syncWaHistory(ctx.userId, ctx.accountId, { chats: chats as never }).catch((err) => {
      logger.warn('WA chats.update failed', { accountId: ctx.accountId, error: (err as Error).message });
    });
  });

  ctx.socket.ev.on('contacts.upsert', (contacts) => {
    if (sessions.get(ctx.accountId) !== ctx || ctx.closed) return;
    void syncWaHistory(ctx.userId, ctx.accountId, { contacts: contacts as never }).catch((err) => {
      logger.warn('WA contacts.upsert failed', { accountId: ctx.accountId, error: (err as Error).message });
    });
  });

  ctx.socket.ev.on('contacts.update', (contacts) => {
    if (sessions.get(ctx.accountId) !== ctx || ctx.closed) return;
    void syncWaHistory(ctx.userId, ctx.accountId, { contacts: contacts as never }).catch((err) => {
      logger.warn('WA contacts.update failed', { accountId: ctx.accountId, error: (err as Error).message });
    });
  });
}

/**
 * Resolve phone number from any WhatsApp message key (handling standard PN, LID, and group participants).
 */
export async function resolveJidToPhone(
  ctx: WaContext,
  m: { key?: { remoteJid?: string | null; remoteJidAlt?: string | null; participant?: string | null; participantAlt?: string | null } },
): Promise<string> {
  const key = m.key;
  if (!key) return '';

  // 1. Direct phone JID in remoteJidAlt or participantAlt
  if (key.remoteJidAlt && key.remoteJidAlt.endsWith('@s.whatsapp.net')) {
    return cleanJidToPhone(key.remoteJidAlt);
  }
  if (key.participantAlt && key.participantAlt.endsWith('@s.whatsapp.net')) {
    return cleanJidToPhone(key.participantAlt);
  }

  const remote = key.remoteJid || '';

  // Filter out broadcast and newsletters
  if (remote === 'status@broadcast' || remote.endsWith('@newsletter')) {
    return '';
  }

  // 2. Standard direct phone JID
  if (remote.endsWith('@s.whatsapp.net')) {
    return cleanJidToPhone(remote);
  }

  // 3. Group participant
  if (remote.endsWith('@g.us')) {
    if (key.participantAlt) return cleanJidToPhone(key.participantAlt);
    if (key.participant && key.participant.endsWith('@s.whatsapp.net')) {
      return cleanJidToPhone(key.participant);
    }
  }

  // 4. LID resolving via Baileys lidMapping store
  if (remote.endsWith('@lid')) {
    try {
      const lidMapping = (ctx.socket as Record<string, any>)?.signalRepository?.lidMapping;
      if (lidMapping && typeof lidMapping.getPNForLID === 'function') {
        const pn = await lidMapping.getPNForLID(remote);
        if (pn) return cleanJidToPhone(pn);
      }
    } catch {
      /* ignore */
    }
  }

  return cleanJidToPhone(remote);
}

export function extractTextFromRaw(m: { message?: unknown }): string | null {
  if (!m || !m.message) return null;
  let msg = m.message as Record<string, any>;

  // Recursively unwrap ephemeral/viewOnce/documentWithCaption wrappers
  let depth = 0;
  while (depth < 10 && msg) {
    if (msg.ephemeralMessage?.message) {
      msg = msg.ephemeralMessage.message;
    } else if (msg.viewOnceMessage?.message) {
      msg = msg.viewOnceMessage.message;
    } else if (msg.viewOnceMessageV2?.message) {
      msg = msg.viewOnceMessageV2.message;
    } else if (msg.viewOnceMessageV2Extension?.message) {
      msg = msg.viewOnceMessageV2Extension.message;
    } else if (msg.documentWithCaptionMessage?.message) {
      msg = msg.documentWithCaptionMessage.message;
    } else if (msg.protocolMessage?.editedMessage) {
      msg = msg.protocolMessage.editedMessage;
    } else if (msg.message) {
      msg = msg.message;
    } else {
      break;
    }
    depth++;
  }

  if (typeof msg.conversation === 'string' && msg.conversation.trim()) {
    return msg.conversation.trim();
  }
  if (typeof msg.extendedTextMessage?.text === 'string' && msg.extendedTextMessage.text.trim()) {
    return msg.extendedTextMessage.text.trim();
  }
  if (typeof msg.reactionMessage?.text === 'string' && msg.reactionMessage.text.trim()) {
    return `${msg.reactionMessage.text} [Реакция]`;
  }
  if (typeof msg.imageMessage?.caption === 'string' && msg.imageMessage.caption.trim()) {
    return msg.imageMessage.caption.trim();
  }
  if (msg.imageMessage) return '📷 [Фотография]';
  if (typeof msg.videoMessage?.caption === 'string' && msg.videoMessage.caption.trim()) {
    return msg.videoMessage.caption.trim();
  }
  if (msg.videoMessage) return '🎥 [Видео]';
  if (msg.audioMessage) return '🎵 [Голосовое сообщение]';
  if (msg.ptvMessage) return '🎥 [Видеосообщение]';
  if (msg.stickerMessage) return '🎨 [Стикер]';
  if (typeof msg.documentMessage?.fileName === 'string' && msg.documentMessage.fileName.trim()) {
    return `📄 [Документ: ${msg.documentMessage.fileName.trim()}]`;
  }
  if (msg.documentMessage) return '📄 [Документ]';
  if (msg.contactMessage?.displayName) return `👤 [Контакт: ${msg.contactMessage.displayName}]`;
  if (msg.contactsArrayMessage) return '👥 [Контакты]';
  if (msg.locationMessage || msg.liveLocationMessage) return '📍 [Геолокация]';
  if (msg.pollCreationMessage?.name) return `📊 [Опрос: ${msg.pollCreationMessage.name}]`;
  if (msg.buttonsResponseMessage?.selectedDisplayText) {
    return String(msg.buttonsResponseMessage.selectedDisplayText);
  }
  if (msg.templateButtonReplyMessage?.selectedDisplayText) {
    return String(msg.templateButtonReplyMessage.selectedDisplayText);
  }
  if (msg.listResponseMessage?.title) {
    return String(msg.listResponseMessage.title);
  }
  if (msg.interactiveResponseMessage?.body?.text) {
    return String(msg.interactiveResponseMessage.body.text);
  }
  return null;
}

async function buildSocket(auth: AuthenticationState): Promise<WASocket> {
  let version;
  try {
    const res = await fetchLatestWaWebVersion();
    version = res.version;
  } catch {
    version = undefined;
  }
  return makeWASocket({
    version,
    auth,
    logger: pinoLogger as never,
    browser: Browsers.ubuntu('Chrome'),
    markOnlineOnConnect: true,
    printQRInTerminal: false,
    syncFullHistory: true,
    emitOwnEvents: true,
    shouldSyncHistoryMessage: () => true,
    shouldIgnoreJid: (jid) => jid === 'status@broadcast' || jid.endsWith('@newsletter'),
    generateHighQualityLinkPreview: false,
    enableAutoSessionRecreation: true,
    enableRecentMessageCache: true,
    connectTimeoutMs: 60000,
    keepAliveIntervalMs: 25000,
    getMessage: async (key) => {
      if (key?.id) {
        try {
          const found = await prisma.message.findFirst({ where: { opId: key.id } });
          if (found) {
            return { conversation: found.body };
          }
        } catch {
          /* ignore */
        }
      }
      return undefined;
    },
  });
}

/**
 * Start (or resume) a WhatsApp Web session for an account.
 */
const starting = new Map<string, Promise<{ state: WaState; qr: string | null; pairingCode: string | null; error: string | null }>>();

export async function startWaSession(
  userId: string,
  accountId: string,
): Promise<{ state: WaState; qr: string | null; pairingCode: string | null; error: string | null }> {
  const inflight = starting.get(accountId);
  if (inflight) return inflight;

  const promise = (async (): Promise<{ state: WaState; qr: string | null; pairingCode: string | null; error: string | null }> => {
    const existing = sessions.get(accountId);
    if (existing && !existing.closed) {
      if (existing.state === 'CONNECTED' || (existing.state === 'SCANNING' && (existing.qr || existing.pairingCode))) {
        return { state: existing.state, qr: existing.qr, pairingCode: existing.pairingCode, error: existing.error };
      }
    }

    ensureSessionsDir();
    const folder = path.join(sessionsDir, accountId);
    let auth: AuthenticationState;
    let saveCreds: () => Promise<void>;
    try {
      ({ state: auth, saveCreds } = await useMultiFileAuthState(folder));
    } catch (err) {
      logger.warn('WA auth state load failed', { accountId, error: (err as Error).message });
      return { state: 'FAILED', qr: null, pairingCode: null, error: 'Не удалось загрузить сессию.' };
    }

    // Terminate any previous socket instance if present
    if (existing) {
      existing.closed = true;
      try {
        existing.socket.end(undefined);
      } catch {
        /* ignore */
      }
      sessions.delete(accountId);
    }

    const socket = await buildSocket(auth);

    const ctx: WaContext = {
      userId,
      accountId,
      socket,
      state: 'SCANNING',
      qr: null,
      pairingCode: null,
      error: null,
      retryTimer: null,
      closed: false,
      saveCreds,
    };

    sessions.set(accountId, ctx);
    attachEvents(ctx);

    await setState(ctx, 'SCANNING', null);
    return { state: ctx.state, qr: ctx.qr, pairingCode: ctx.pairingCode, error: ctx.error };
  })().finally(() => {
    starting.delete(accountId);
  });

  starting.set(accountId, promise);
  return promise;
}

/** Current session status without creating new socket. */
export function getWaStatus(accountId: string): { state: WaState; qr: string | null; pairingCode: string | null; error: string | null } | null {
  const ctx = sessions.get(accountId);
  if (!ctx || ctx.closed) return null;
  return { state: ctx.state, qr: ctx.qr, pairingCode: ctx.pairingCode, error: ctx.error };
}

/** Request an 8-character pairing code by phone number (no QR scan needed). */
export async function requestWaPairingCode(
  userId: string,
  accountId: string,
  phoneNumber: string,
): Promise<{ state: WaState; pairingCode: string | null; error: string | null }> {
  const cleanPhone = sanitizePhone(phoneNumber);
  if (cleanPhone.length < 9) {
    throw new Error('Укажите корректный номер телефона с кодом страны.');
  }

  let ctx = sessions.get(accountId);
  if (!ctx || ctx.closed) {
    await startWaSession(userId, accountId);
    ctx = sessions.get(accountId);
  }

  if (!ctx || ctx.closed) {
    throw new Error('Не удалось инициализировать сессию WhatsApp.');
  }

  if (ctx.state === 'CONNECTED') {
    return { state: 'CONNECTED', pairingCode: null, error: null };
  }

  try {
    const code = await ctx.socket.requestPairingCode(cleanPhone);
    const formattedCode = code?.match(/.{1,4}/g)?.join('-') ?? code;
    ctx.pairingCode = formattedCode;
    logger.info('WA pairing code issued', { accountId, code: formattedCode });
    emitToUser(userId, 'account.wa.pairing_code', { accountId, code: formattedCode });
    return { state: 'SCANNING', pairingCode: formattedCode, error: null };
  } catch (err) {
    const message = (err as Error).message ?? 'Не удалось сгенерировать код сопряжения.';
    logger.warn('WA pairing code failed', { accountId, error: message });
    return { state: 'FAILED', pairingCode: null, error: message };
  }
}

/** Force a fresh pairing ref: restart session and purge stale folder so brand new QR is issued. */
export async function refreshWaQr(
  userId: string,
  accountId: string,
): Promise<{ state: WaState; qr: string | null; pairingCode: string | null } | null> {
  const existing = sessions.get(accountId);
  if (existing) {
    if (existing.state === 'CONNECTED' && !existing.closed) {
      return { state: existing.state, qr: null, pairingCode: null };
    }
    existing.closed = true;
    if (existing.retryTimer) {
      clearTimeout(existing.retryTimer);
      existing.retryTimer = null;
    }
    try {
      existing.socket.end(undefined);
    } catch {
      /* ignore */
    }
    sessions.delete(accountId);
  }

  // Purge any stale/half-baked credentials on disk
  await purgeSessionFolder(accountId);

  await startWaSession(userId, accountId);
  const fresh = sessions.get(accountId);
  return fresh
    ? { state: fresh.state, qr: fresh.qr, pairingCode: fresh.pairingCode }
    : { state: 'DISCONNECTED', qr: null, pairingCode: null };
}

/** Log out and delete the local session. */
export async function logoutWaSession(accountId: string): Promise<void> {
  const ctx = sessions.get(accountId);
  if (ctx) {
    ctx.closed = true;
    if (ctx.retryTimer) {
      clearTimeout(ctx.retryTimer);
      ctx.retryTimer = null;
    }
    try {
      await ctx.socket.logout();
    } catch {
      /* ignore */
    }
    try {
      ctx.socket.end(undefined);
    } catch {
      /* ignore */
    }
  }
  sessions.delete(accountId);
  await purgeSessionFolder(accountId);

  const acc = await prisma.whatsAppAccount.findUnique({ where: { id: accountId } });
  if (acc) {
    await prisma.gatewayConnection.upsert({
      where: { accountId },
      update: { status: 'DISCONNECTED', lastError: null },
      create: { accountId, provider: 'WHATSAPP_WEB', idInstance: '', apiToken: '', status: 'DISCONNECTED' },
    });
    await prisma.whatsAppAccount.update({
      where: { id: accountId },
      data: { status: acc.status === 'PAUSED' ? 'PAUSED' : 'OFFLINE', lastActiveAt: undefined },
    });
    emitToUser(acc.userId, 'account.gateway.status', { accountId, status: 'DISCONNECTED' });
  }
}

/** Send a text message via an active session. */
export async function sendWaText(
  accountId: string,
  phone: string,
  body: string,
): Promise<{ opId: string }> {
  const ctx = sessions.get(accountId);
  if (!ctx || ctx.closed || ctx.state !== 'CONNECTED') {
    throw new Error('WA_SESSION_NOT_CONNECTED');
  }
  const result = await ctx.socket.sendMessage(toWaJid(phone), { text: body });
  return { opId: result?.key?.id ?? '' };
}

/** Remove in-memory session state for an account. */
export function removeSession(accountId: string): void {
  const ctx = sessions.get(accountId);
  if (ctx) {
    ctx.closed = true;
    if (ctx.retryTimer) {
      clearTimeout(ctx.retryTimer);
      ctx.retryTimer = null;
    }
  }
  sessions.delete(accountId);
}

/** Delete the on-disk session folder so a brand-new pairing ref is issued. */
export async function purgeSessionFolder(accountId: string): Promise<void> {
  const folder = path.join(sessionsDir, accountId);
  try {
    await fs.promises.rm(folder, { recursive: true, force: true });
    logger.info('WA session folder purged', { accountId });
  } catch (err) {
    logger.warn('session folder purge failed', { accountId, error: (err as Error).message });
  }
}

/**
 * Trigger active WhatsApp chat & app state resync.
 */
export async function triggerWaSync(userId: string, accountId: string): Promise<{ ok: boolean; state: WaState }> {
  const existing = sessions.get(accountId);
  if (!existing || existing.closed || existing.state !== 'CONNECTED') {
    const started = await startWaSession(userId, accountId);
    return { ok: true, state: started.state };
  }
  try {
    await existing.socket.resyncAppState(['critical_block', 'critical_unblock_low', 'regular_high', 'regular_low', 'regular'], false);
  } catch {
    /* ignore */
  }
  return { ok: true, state: existing.state };
}

/** Resume previously-logged-in sessions after a server restart. */
export async function resumeWaSessions(): Promise<void> {
  const rows = await prisma.gatewayConnection.findMany({
    where: { provider: 'WHATSAPP_WEB', status: { in: ['SCANNING', 'CONNECTED'] } },
    include: { account: { select: { userId: true } } },
  });
  for (const row of rows) {
    void startWaSession(row.account.userId, row.accountId).catch((err) => {
      logger.warn('WA resume failed', { accountId: row.accountId, error: (err as Error).message });
    });
  }
}

export { toWaJid, jidToPhone };